# AboutOss is an utility library to retrieve and display
# opensource licenses in Android applications.
#
# Copyright (C) 2023-2025 by Frederic-Charles Barthelery.
#
# This file is part of AboutOss.
#
# AboutOss is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AboutOss is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AboutOss.  If not, see <http://www.gnu.org/licenses/>.

[versions]
android-gradle-plugin = "8.13.0"
dokka = "2.0.0"
kotlin = "2.2.21"
jetbrains-compose-multiplatform = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.0"
okio = "3.16.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
androidx-activity = "1.11.0"
androidx-navigation = "2.9.4"
androidx-compose-bom = "2025.09.00"
jetbrains-androidx-lifecycle = "2.9.4"
jetbrains-androidx-navigation = "2.9.0"
jetbrains-compose-material3AdaptiveNavigation = "1.1.2"
jetbrains-compose-materialIconsCore = "1.7.3"
jetbrains-compose-ui = "1.9.0"
geekdroid = "geekttrss-1.6.8"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio"}
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines"}
geekdroid = { module = "com.geekorum.geekdroid:geekdroid", version.ref = "geekdroid" }

jetbrains-androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-viewmodel= { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-viewModelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-androidx-lifecycle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref="androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref="androidx-activity" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref="androidx-navigation" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation" }

jetbrains-compose-materialIconsCore = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "jetbrains-compose-materialIconsCore" }
jetbrains-compose-material3AdaptiveNavigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "jetbrains-compose-material3AdaptiveNavigation" }
jetbrains-compose-uiBackhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrains-compose-ui" }

androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
dokka-android-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokka" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
jetbrains-compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose-multiplatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-gms-oss-license = { id = "com.google.android.gms.oss-licenses-plugin", version = "0.10.6" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }

[bundles]

